In [48]:
import pandas as pd
from re import sub

#one error found so far is that in the 'engo531_lab1.ext' file extra tabs are used which means that the file needs to be cleaned in order to properly read in the data
#second error was found from additional tabs in the int file
#int file also contain inconsistant spacing delimeters which resulted in additional processing

def read_tie(filename = 'engo531_lab1.tie'):
    """
    Desc:
        Reads in the tie points as returns dataframe of the values
    In:
        filename, default set to lab1 filename
    Out:
        dataframe with columns "X, Y, Z" and index set to point_id
    """
    df = pd.read_csv(filename, sep = "\t", header = None)
    df.columns =  columns = ["point_id", "X", "Y", "Z"] 
    df = df.set_index("point_id")
    
    return df

def read_ext(filename = 'engo531_lab1.ext'):
    """
    Desc:
        Reads in the tie points as returns dataframe of the values
    In:
        filename, default set to lab1 filename
    Out:
        dataframe with columns "image_id","camera_id","Xc", "Yc", "Zc", "w", "o", "k" and index set to natural incrementation
    """
    df = pd.read_csv(filename, sep = "\t", header = None)
    
    #cleaning the data
    df = df.drop([8,9,10,11,12,13,14], axis=1)
    
    df.columns =  columns = ["image_id","camera_id","Xc", "Yc", "Zc", "w", "o", "k"] 
    
    return df
    
def read_int(filename = 'engo531_lab1.int'):
    """
    Desc:
        Reads in the tie points as returns dataframe of the values
    In:
        filename, default set to lab1 filename
    Out:
        dataframe with columns "X, Y, Z" and index set to natural incrementation
    """
    df = pd.read_csv(filename, sep = "\t", header = None)
    
    #cleaning the data
    df = df.drop([0], axis=1)
    
    #break column 2 into the proper X, Y, Z string
    
    
    #df.columns =  columns = ["image_id","camera_id","Xc", "Yc", "Zc", "w", "o", "k"] 
    return df
#s = str(read_int()[2])
#s.split(" ")
test = df = read_int()
#df.loc[0][2].split(" ")
#sub("<[^>]+>|[ .]", "", test)

TypeError: expected string or bytes-like object

In [14]:

#df[0].to_list()

             X     Y     Z
point_id
71        2200  2500 -1200
85        2800  2000   500
89        2800  2000  -200
132       1800  3000  -800
133       2300  2400  -600